title: Yoma Akoni's Homepage
page-top-title: Ogheneyoma ('Yoma') Akoni
top-section-bg-text: Computer Science - Artificial Intelligence
home-subtitle: Yoma Akoni
copyright-text: '&copy; Yoma Akoni 2025. All Rights Reserved.'
